import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Adding category, brand, and products...\n');

  // ====================================
  // GET VENDOR ID
  // ====================================
  const vendor = await prisma.vendor.findFirst({
    where: { slug: 'antique-oud' }
  });

  if (!vendor) {
    throw new Error('Vendor "antique-oud" not found. Run seed-no-products.ts first.');
  }

  console.log('✅ Found vendor:', vendor.businessName, '(ID:', vendor.id + ')');

  // ====================================
  // ADD LIMITED-EDITION CATEGORY
  // ====================================
  console.log('\n📁 Adding limited-edition category...');

  const limitedEditionCategory = await prisma.category.upsert({
    where: { slug: 'limited-edition' },
    update: {},
    create: {
      name: 'Limited Edition',
      nameAr: 'إصدار محدود',
      slug: 'limited-edition',
      description: 'Exclusive limited edition collections and gift sets',
      descriptionAr: 'مجموعات حصرية وهدايا محدودة الإصدار',
      image: '/perfume-images/antik-posts2.jpg',
      icon: '✨',
      sortOrder: 7,
      isActive: true,
    },
  });
  console.log('✅ Created category:', limitedEditionCategory.name);

  // ====================================
  // GET EXISTING CATEGORIES
  // ====================================
  const oudCategory = await prisma.category.findUnique({ where: { slug: 'oud' } });
  const dehnalOudCategory = await prisma.category.findUnique({ where: { slug: 'dehnal-oud' } });
  const perfumesCategory = await prisma.category.findUnique({ where: { slug: 'perfumes' } });
  const allOverSprayCategory = await prisma.category.findUnique({ where: { slug: 'all-over-spray' } });

  if (!oudCategory || !dehnalOudCategory || !perfumesCategory || !allOverSprayCategory) {
    throw new Error('Missing required categories. Run seed.ts first.');
  }

  console.log('✅ Found all required categories');

  // ====================================
  // ADD ANTIQUE OUD BRAND
  // ====================================
  console.log('\n🏷️  Adding Antique Oud brand...');

  const antiqueOudBrand = await prisma.brand.upsert({
    where: { slug: 'antique-oud' },
    update: {},
    create: {
      name: 'Antique Oud',
      nameAr: 'أنتيك العود',
      slug: 'antique-oud',
      description: 'Premium Traditional Arabic Oud & Fragrances',
      descriptionAr: 'أرقى أنواع العود والعطور العربية الأصيلة',
      logo: '/images/antique-oud-logo.svg',
      isActive: true,
    },
  });
  console.log('✅ Created brand:', antiqueOudBrand.name);

  // ====================================
  // ADD PRODUCTS
  // ====================================
  console.log('\n🧴 Adding products...\n');

  // Helper function to create product
  const createProduct = async (product: any) => {
    const created = await prisma.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    });
    console.log(`  ✓ ${created.name}`);
    return created;
  };

  // ========== OUD (AGARWOOD CHIPS) - 13 Products ==========
  console.log('📦 Oud (Agarwood Chips) - 13 products:');

  const oudProducts = [
    {
      name: 'Indian Dugga VIP',
      nameAr: 'عود هندي دقة VIP',
      slug: 'indian-dugga-vip',
      description: 'Premium Indian Dugga oud chips with rich, deep woody aroma. A VIP selection for connoisseurs.',
      descriptionAr: 'رقائق عود هندي دقة فاخرة برائحة خشبية عميقة وغنية. اختيار VIP للخبراء.',
      price: 1200,
      compareAtPrice: 1500,
      sku: 'OUD-IND-DUG-VIP',
      stock: 25,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'INDIA',
      format: 'CHIPS',
      longevity: '8-12 hours',
      sillage: 'Strong',
      coinsToAward: 120,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Trat Agarwood Chips VIP',
      nameAr: 'رقائق عود تراث VIP',
      slug: 'trat-agarwood-chips-vip',
      description: 'Exquisite Trat agarwood chips with complex sweet and woody notes. VIP grade quality.',
      descriptionAr: 'رقائق عود تراث رائعة بنوتات حلوة وخشبية معقدة. جودة درجة VIP.',
      price: 1500,
      compareAtPrice: 1800,
      sku: 'OUD-TRAT-VIP',
      stock: 20,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'THAILAND',
      format: 'CHIPS',
      longevity: '10-14 hours',
      sillage: 'Very Strong',
      coinsToAward: 150,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Malaki Majalis',
      nameAr: 'ملكي مجالس',
      slug: 'malaki-majalis',
      description: 'Royal oud perfect for majalis gatherings. Rich and inviting aroma.',
      descriptionAr: 'عود ملكي مثالي لمجالس الضيافة. رائحة غنية وجذابة.',
      price: 900,
      compareAtPrice: 1100,
      sku: 'OUD-MAL-MAJ',
      stock: 30,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '6-10 hours',
      sillage: 'Strong',
      coinsToAward: 90,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Royal Indian Syoufi',
      nameAr: 'عود هندي سيوفي ملكي',
      slug: 'royal-indian-syoufi',
      description: 'Premium Royal Indian Syoufi oud with distinctive sharp and clean woody profile.',
      descriptionAr: 'عود هندي سيوفي ملكي فاخر بنكهة خشبية نقية ومميزة.',
      price: 1100,
      compareAtPrice: 1350,
      sku: 'OUD-IND-SYO-ROY',
      stock: 22,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'INDIA',
      format: 'CHIPS',
      longevity: '8-12 hours',
      sillage: 'Strong',
      coinsToAward: 110,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Malaki Vietnami',
      nameAr: 'ملكي فيتنامي',
      slug: 'malaki-vietnami',
      description: 'Royal Vietnamese oud with sweet, honeyed undertones and smooth finish.',
      descriptionAr: 'عود فيتنامي ملكي بنوتات عسلية حلوة ونهاية ناعمة.',
      price: 850,
      compareAtPrice: 1000,
      sku: 'OUD-MAL-VIET',
      stock: 28,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '6-10 hours',
      sillage: 'Moderate',
      coinsToAward: 85,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Malaki Mori',
      nameAr: 'ملكي موري',
      slug: 'malaki-mori',
      description: 'Royal Mori oud blend with balanced earthy and sweet characteristics.',
      descriptionAr: 'مزيج عود موري ملكي بخصائص ترابية وحلوة متوازنة.',
      price: 800,
      compareAtPrice: 950,
      sku: 'OUD-MAL-MORI',
      stock: 35,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '6-8 hours',
      sillage: 'Moderate',
      coinsToAward: 80,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Mori VIP',
      nameAr: 'موري VIP',
      slug: 'mori-vip',
      description: 'VIP grade Mori oud with enhanced complexity and longer lasting burn.',
      descriptionAr: 'عود موري درجة VIP بتعقيد معزز واحتراق أطول.',
      price: 1000,
      compareAtPrice: 1200,
      sku: 'OUD-MORI-VIP',
      stock: 18,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '8-12 hours',
      sillage: 'Strong',
      coinsToAward: 100,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Mori Malaki',
      nameAr: 'موري ملكي',
      slug: 'mori-malaki',
      description: 'Premium Mori Malaki blend combining the best of both varieties.',
      descriptionAr: 'مزيج موري ملكي فاخر يجمع أفضل ما في النوعين.',
      price: 950,
      compareAtPrice: 1150,
      sku: 'OUD-MORI-MAL',
      stock: 24,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '8-10 hours',
      sillage: 'Strong',
      coinsToAward: 95,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Salla VIP',
      nameAr: 'سلا VIP',
      slug: 'salla-vip',
      description: 'Exceptional Salla VIP oud with refined aromatic profile and lasting presence.',
      descriptionAr: 'عود سلا VIP استثنائي بنكهة عطرية راقية وحضور دائم.',
      price: 1300,
      compareAtPrice: 1550,
      sku: 'OUD-SALLA-VIP',
      stock: 15,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '10-14 hours',
      sillage: 'Very Strong',
      coinsToAward: 130,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Elite Trad',
      nameAr: 'عود تراث النخبة',
      slug: 'elite-trad',
      description: 'Elite grade traditional oud with heritage quality and exceptional depth.',
      descriptionAr: 'عود تقليدي من درجة النخبة بجودة تراثية وعمق استثنائي.',
      price: 1400,
      compareAtPrice: 1700,
      sku: 'OUD-ELITE-TRAD',
      stock: 12,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '10-14 hours',
      sillage: 'Very Strong',
      coinsToAward: 140,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Indian Syoufi Nagaland VIP',
      nameAr: 'عود هندي سيوفي ناجالاند VIP',
      slug: 'indian-syoufi-nagaland-vip',
      description: 'Rare Nagaland region Indian Syoufi oud. VIP selection with unique terroir characteristics.',
      descriptionAr: 'عود هندي سيوفي نادر من منطقة ناجالاند. اختيار VIP بخصائص تربة فريدة.',
      price: 1600,
      compareAtPrice: 1900,
      sku: 'OUD-IND-NAG-VIP',
      stock: 10,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'INDIA',
      format: 'CHIPS',
      longevity: '12-16 hours',
      sillage: 'Very Strong',
      coinsToAward: 160,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Ancient Maroki Asgor Jungle',
      nameAr: 'عود ماروكي أسغور الغابة العتيق',
      slug: 'ancient-maroki-asgor-jungle',
      description: 'Ancient wild jungle Maroki oud from Asgor region. Deep, complex, and hauntingly beautiful.',
      descriptionAr: 'عود ماروكي بري قديم من منطقة أسغور الغابة. عميق ومعقد وجميل بشكل ساحر.',
      price: 2000,
      compareAtPrice: 2400,
      sku: 'OUD-MAR-ASG-ANC',
      stock: 8,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'CHIPS',
      longevity: '12-18 hours',
      sillage: 'Very Strong',
      coinsToAward: 200,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Ancient Khao Yai Jungle (Rare Collection)',
      nameAr: 'عود خاو ياي الغابة العتيق (مجموعة نادرة)',
      slug: 'ancient-khao-yai-jungle-rare',
      description: 'Extremely rare ancient oud from Khao Yai jungle. Collectors piece with unmatched depth and character.',
      descriptionAr: 'عود قديم نادر للغاية من غابة خاو ياي. قطعة جامعين بعمق وشخصية لا مثيل لها.',
      price: 2500,
      compareAtPrice: 3000,
      sku: 'OUD-KHAO-RARE',
      stock: 5,
      images: [],
      categoryId: oudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '10g',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'THAILAND',
      format: 'CHIPS',
      longevity: '14-20 hours',
      sillage: 'Very Strong',
      coinsToAward: 250,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
      collection: 'RARE',
    },
  ];

  for (const product of oudProducts) {
    await createProduct(product);
  }

  // ========== DEHNAL OUD (OUD OILS) - 8 Products ==========
  console.log('\n📦 Oud Oils (Dehn Al Oud) - 8 products:');

  const oudOilProducts = [
    {
      name: 'Old Trat Oud Oil',
      nameAr: 'دهن عود تراث قديم',
      slug: 'old-trat-oud-oil',
      description: 'Aged Trat oud oil with mature, refined character. Deep woody notes with subtle sweetness.',
      descriptionAr: 'دهن عود تراث معتق بشخصية ناضجة وراقية. نوتات خشبية عميقة مع حلاوة خفيفة.',
      price: 1800,
      compareAtPrice: 2200,
      sku: 'DOIL-TRAT-OLD',
      stock: 15,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'THAILAND',
      format: 'OIL',
      longevity: '12-18 hours',
      sillage: 'Strong',
      coinsToAward: 180,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Elite Trat Oud Oil',
      nameAr: 'دهن عود تراث النخبة',
      slug: 'elite-trat-oud-oil',
      description: 'Elite grade Trat oud oil. Exceptional purity and aromatic complexity.',
      descriptionAr: 'دهن عود تراث من درجة النخبة. نقاء استثنائي وتعقيد عطري.',
      price: 2200,
      compareAtPrice: 2600,
      sku: 'DOIL-TRAT-ELITE',
      stock: 12,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'THAILAND',
      format: 'OIL',
      longevity: '14-20 hours',
      sillage: 'Very Strong',
      coinsToAward: 220,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Sweet Trat Oud Oil',
      nameAr: 'دهن عود تراث حلو',
      slug: 'sweet-trat-oud-oil',
      description: 'Sweet profile Trat oud oil with honeyed notes and smooth finish.',
      descriptionAr: 'دهن عود تراث بنكهة حلوة مع نوتات عسلية ونهاية ناعمة.',
      price: 1600,
      compareAtPrice: 1900,
      sku: 'DOIL-TRAT-SWEET',
      stock: 18,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'NICHE',
      region: 'THAILAND',
      format: 'OIL',
      longevity: '10-16 hours',
      sillage: 'Strong',
      coinsToAward: 160,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Old Malino Oud Oil',
      nameAr: 'دهن عود مالينو قديم',
      slug: 'old-malino-oud-oil',
      description: 'Aged Malino oud oil with rich, resinous depth and complex character.',
      descriptionAr: 'دهن عود مالينو معتق بعمق راتنجي غني وشخصية معقدة.',
      price: 2000,
      compareAtPrice: 2400,
      sku: 'DOIL-MALINO-OLD',
      stock: 10,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'OIL',
      longevity: '12-18 hours',
      sillage: 'Very Strong',
      coinsToAward: 200,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Old Maroki Oud Oil (Rare)',
      nameAr: 'دهن عود ماروكي قديم (نادر)',
      slug: 'old-maroki-oud-oil-rare',
      description: 'Rare aged Maroki oud oil. Exceptionally complex with decades of maturation.',
      descriptionAr: 'دهن عود ماروكي معتق نادر. معقد بشكل استثنائي مع عقود من النضج.',
      price: 3000,
      compareAtPrice: 3500,
      sku: 'DOIL-MAROKI-RARE',
      stock: 5,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'UAE',
      format: 'OIL',
      longevity: '16-24 hours',
      sillage: 'Very Strong',
      coinsToAward: 300,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
      collection: 'RARE',
    },
    {
      name: 'Jaya Oud Oil (Rare)',
      nameAr: 'دهن عود جايا (نادر)',
      slug: 'jaya-oud-oil-rare',
      description: 'Rare Jaya oud oil with distinctive floral-woody profile. Collectors edition.',
      descriptionAr: 'دهن عود جايا نادر بنكهة زهرية-خشبية مميزة. إصدار جامعين.',
      price: 2800,
      compareAtPrice: 3300,
      sku: 'DOIL-JAYA-RARE',
      stock: 6,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'floral',
      productType: 'NICHE',
      region: 'UAE',
      format: 'OIL',
      longevity: '14-22 hours',
      sillage: 'Very Strong',
      coinsToAward: 280,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
      collection: 'RARE',
    },
    {
      name: 'Elite Prachin Oud Oil',
      nameAr: 'دهن عود براشين النخبة',
      slug: 'elite-prachin-oud-oil',
      description: 'Elite Prachin oud oil with refined Thai characteristics and lasting power.',
      descriptionAr: 'دهن عود براشين النخبة بخصائص تايلندية راقية وقوة ثبات.',
      price: 2400,
      compareAtPrice: 2800,
      sku: 'DOIL-PRACHIN-ELITE',
      stock: 8,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'THAILAND',
      format: 'OIL',
      longevity: '14-20 hours',
      sillage: 'Very Strong',
      coinsToAward: 240,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Old Indian Syoufi Oud Oil',
      nameAr: 'دهن عود هندي سيوفي قديم',
      slug: 'old-indian-syoufi-oud-oil',
      description: 'Aged Indian Syoufi oud oil with bold, resinous character and exceptional depth.',
      descriptionAr: 'دهن عود هندي سيوفي معتق بشخصية راتنجية جريئة وعمق استثنائي.',
      price: 2600,
      compareAtPrice: 3100,
      sku: 'DOIL-IND-SYO-OLD',
      stock: 7,
      images: [],
      categoryId: dehnalOudCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '3ml',
      concentration: 'Pure Oil',
      gender: 'unisex',
      scentFamily: 'woody',
      productType: 'NICHE',
      region: 'INDIA',
      format: 'OIL',
      longevity: '14-22 hours',
      sillage: 'Very Strong',
      coinsToAward: 260,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
  ];

  for (const product of oudOilProducts) {
    await createProduct(product);
  }

  // ========== PERFUMES - 5 Products ==========
  console.log('\n📦 Perfumes - 5 products:');

  const perfumeProducts = [
    {
      name: 'Umsiya',
      nameAr: 'أمسية',
      slug: 'umsiya',
      description: 'An enchanting evening fragrance with warm oriental notes. Perfect for special nights.',
      descriptionAr: 'عطر مسائي ساحر بنوتات شرقية دافئة. مثالي للليالي الخاصة.',
      price: 350,
      compareAtPrice: 420,
      sku: 'PERF-UMSIYA',
      stock: 40,
      images: [],
      categoryId: perfumesCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '50ml',
      concentration: 'Eau de Parfum',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'OUR_BRAND',
      region: 'UAE',
      format: 'SPRAY',
      topNotes: 'Bergamot, Saffron',
      heartNotes: 'Rose, Oud',
      baseNotes: 'Amber, Musk, Sandalwood',
      longevity: '8-12 hours',
      sillage: 'Strong',
      occasion: 'PARTY,WEDDING',
      coinsToAward: 35,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Hikayah',
      nameAr: 'حكاية',
      slug: 'hikayah',
      description: 'A storytelling fragrance that unfolds through the day. Rich and mysterious.',
      descriptionAr: 'عطر يروي قصة تتكشف على مدار اليوم. غني وغامض.',
      price: 380,
      compareAtPrice: 450,
      sku: 'PERF-HIKAYAH',
      stock: 35,
      images: [],
      categoryId: perfumesCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '50ml',
      concentration: 'Eau de Parfum',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'OUR_BRAND',
      region: 'UAE',
      format: 'SPRAY',
      topNotes: 'Cardamom, Pink Pepper',
      heartNotes: 'Jasmine, Oud',
      baseNotes: 'Vanilla, Benzoin, Musk',
      longevity: '10-14 hours',
      sillage: 'Strong',
      occasion: 'PARTY,RAMADAN',
      coinsToAward: 38,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Nesayim',
      nameAr: 'نسايم',
      slug: 'nesayim',
      description: 'Fresh breeze fragrance with light floral and citrus notes. Perfect for daily wear.',
      descriptionAr: 'عطر نسيم منعش بنوتات زهرية وحمضية خفيفة. مثالي للارتداء اليومي.',
      price: 320,
      compareAtPrice: 380,
      sku: 'PERF-NESAYIM',
      stock: 50,
      images: [],
      categoryId: perfumesCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '50ml',
      concentration: 'Eau de Parfum',
      gender: 'unisex',
      scentFamily: 'fresh',
      productType: 'OUR_BRAND',
      region: 'UAE',
      format: 'SPRAY',
      topNotes: 'Lemon, Bergamot, Green Apple',
      heartNotes: 'White Flowers, Lily',
      baseNotes: 'White Musk, Cedar',
      longevity: '6-10 hours',
      sillage: 'Moderate',
      occasion: 'DAILY,OFFICE',
      coinsToAward: 32,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Kunooz',
      nameAr: 'كنوز',
      slug: 'kunooz',
      description: 'A treasure of Arabian fragrances. Rich, opulent, and unforgettable.',
      descriptionAr: 'كنز من العطور العربية. غني وفخم ولا يُنسى.',
      price: 400,
      compareAtPrice: 480,
      sku: 'PERF-KUNOOZ',
      stock: 30,
      images: [],
      categoryId: perfumesCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '50ml',
      concentration: 'Eau de Parfum',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'OUR_BRAND',
      region: 'UAE',
      format: 'SPRAY',
      topNotes: 'Saffron, Rose',
      heartNotes: 'Oud, Incense',
      baseNotes: 'Amber, Leather, Musk',
      longevity: '10-16 hours',
      sillage: 'Very Strong',
      occasion: 'WEDDING,EID,RAMADAN',
      coinsToAward: 40,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Hams',
      nameAr: 'همس',
      slug: 'hams',
      description: 'A whisper of elegance. Soft, intimate, and deeply personal fragrance.',
      descriptionAr: 'همسة من الأناقة. عطر ناعم وحميم وشخصي للغاية.',
      price: 340,
      compareAtPrice: 400,
      sku: 'PERF-HAMS',
      stock: 45,
      images: [],
      categoryId: perfumesCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '50ml',
      concentration: 'Eau de Parfum',
      gender: 'women',
      scentFamily: 'floral',
      productType: 'OUR_BRAND',
      region: 'UAE',
      format: 'SPRAY',
      topNotes: 'Peach, Pear',
      heartNotes: 'Rose, Peony, Jasmine',
      baseNotes: 'White Musk, Sandalwood',
      longevity: '8-12 hours',
      sillage: 'Moderate',
      occasion: 'DAILY,PARTY',
      coinsToAward: 34,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
  ];

  for (const product of perfumeProducts) {
    await createProduct(product);
  }

  // ========== BODY SPRAY (ALL OVER SPRAYS) - 5 Products ==========
  console.log('\n📦 All Over Sprays - 5 products:');

  const allOverSprayProducts = [
    {
      name: 'Chic',
      nameAr: 'شيك',
      slug: 'chic-body-spray',
      description: 'Modern and sophisticated all-over spray for the contemporary individual.',
      descriptionAr: 'بخاخ عصري وأنيق للشخص المعاصر.',
      price: 120,
      compareAtPrice: 150,
      sku: 'SPRAY-CHIC',
      stock: 80,
      images: [],
      categoryId: allOverSprayCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '100ml',
      concentration: 'Body Spray',
      gender: 'unisex',
      scentFamily: 'fresh',
      productType: 'BODY_SPRAY',
      region: 'UAE',
      format: 'SPRAY',
      longevity: '4-6 hours',
      sillage: 'Moderate',
      occasion: 'DAILY,OFFICE',
      coinsToAward: 12,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Hiyam',
      nameAr: 'هيام',
      slug: 'hiyam-body-spray',
      description: 'Passionate and warm all-over spray with romantic undertones.',
      descriptionAr: 'بخاخ عاطفي ودافئ بنغمات رومانسية.',
      price: 110,
      compareAtPrice: 140,
      sku: 'SPRAY-HIYAM',
      stock: 75,
      images: [],
      categoryId: allOverSprayCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '100ml',
      concentration: 'Body Spray',
      gender: 'women',
      scentFamily: 'floral',
      productType: 'BODY_SPRAY',
      region: 'UAE',
      format: 'SPRAY',
      longevity: '4-6 hours',
      sillage: 'Moderate',
      occasion: 'DAILY,PARTY',
      coinsToAward: 11,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Fajr',
      nameAr: 'فجر',
      slug: 'fajr-body-spray',
      description: 'Fresh morning-inspired all-over spray. Clean and uplifting.',
      descriptionAr: 'بخاخ مستوحى من نسيم الصباح. منعش ومنشط.',
      price: 100,
      compareAtPrice: 125,
      sku: 'SPRAY-FAJR',
      stock: 90,
      images: [],
      categoryId: allOverSprayCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '100ml',
      concentration: 'Body Spray',
      gender: 'unisex',
      scentFamily: 'fresh',
      productType: 'BODY_SPRAY',
      region: 'UAE',
      format: 'SPRAY',
      longevity: '3-5 hours',
      sillage: 'Light',
      occasion: 'DAILY,OFFICE',
      coinsToAward: 10,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Gharam',
      nameAr: 'غرام',
      slug: 'gharam-body-spray',
      description: 'Seductive and captivating all-over spray for unforgettable impressions.',
      descriptionAr: 'بخاخ ساحر وجذاب لانطباعات لا تُنسى.',
      price: 115,
      compareAtPrice: 145,
      sku: 'SPRAY-GHARAM',
      stock: 70,
      images: [],
      categoryId: allOverSprayCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '100ml',
      concentration: 'Body Spray',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'BODY_SPRAY',
      region: 'UAE',
      format: 'SPRAY',
      longevity: '4-6 hours',
      sillage: 'Moderate',
      occasion: 'PARTY,DAILY',
      coinsToAward: 12,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Ghazal',
      nameAr: 'غزال',
      slug: 'ghazal-body-spray',
      description: 'Graceful and elegant all-over spray with soft musky notes.',
      descriptionAr: 'بخاخ رشيق وأنيق بنوتات مسك ناعمة.',
      price: 105,
      compareAtPrice: 130,
      sku: 'SPRAY-GHAZAL',
      stock: 85,
      images: [],
      categoryId: allOverSprayCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '100ml',
      concentration: 'Body Spray',
      gender: 'women',
      scentFamily: 'musky',
      productType: 'BODY_SPRAY',
      region: 'UAE',
      format: 'SPRAY',
      longevity: '4-6 hours',
      sillage: 'Light',
      occasion: 'DAILY',
      coinsToAward: 11,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
  ];

  for (const product of allOverSprayProducts) {
    await createProduct(product);
  }

  // ========== LIMITED EDITION - 3 Products ==========
  console.log('\n📦 Limited Edition - 3 products:');

  const limitedEditionProducts = [
    {
      name: 'Antique Luxury Box',
      nameAr: 'صندوق أنتيك الفاخر',
      slug: 'antique-luxury-box',
      description: 'Exclusive luxury gift box featuring premium oud, perfume, and accessories. The ultimate gift.',
      descriptionAr: 'صندوق هدايا فاخر حصري يتضمن عود ممتاز وعطر وإكسسوارات. الهدية المثالية.',
      price: 1200,
      compareAtPrice: 1500,
      sku: 'LTD-LUXURY-BOX',
      stock: 20,
      images: [],
      categoryId: limitedEditionCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: 'Set',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'GIFT_SET',
      region: 'UAE',
      format: 'GIFT_SET',
      occasion: 'WEDDING,EID,RAMADAN',
      collection: 'LIMITED',
      coinsToAward: 120,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Gift Bag',
      nameAr: 'حقيبة الهدايا',
      slug: 'gift-bag',
      description: 'Elegant gift bag with curated selection of Antique Oud favorites.',
      descriptionAr: 'حقيبة هدايا أنيقة مع مجموعة مختارة من منتجات أنتيك العود المفضلة.',
      price: 450,
      compareAtPrice: 550,
      sku: 'LTD-GIFT-BAG',
      stock: 35,
      images: [],
      categoryId: limitedEditionCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: 'Set',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'GIFT_SET',
      region: 'UAE',
      format: 'GIFT_SET',
      occasion: 'WEDDING,EID',
      collection: 'LIMITED',
      coinsToAward: 45,
      isFeatured: false,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
    {
      name: 'Irth (Heritage)',
      nameAr: 'إرث',
      slug: 'irth-heritage',
      description: 'Heritage collection perfume celebrating traditional Arabian perfumery. Limited edition.',
      descriptionAr: 'عطر مجموعة التراث يحتفي بفن العطور العربية التقليدية. إصدار محدود.',
      price: 800,
      compareAtPrice: 950,
      sku: 'LTD-IRTH',
      stock: 25,
      images: [],
      categoryId: limitedEditionCategory.id,
      brandId: antiqueOudBrand.id,
      vendorId: vendor.id,
      size: '50ml',
      concentration: 'Eau de Parfum',
      gender: 'unisex',
      scentFamily: 'oriental',
      productType: 'OUR_BRAND',
      region: 'UAE',
      format: 'SPRAY',
      topNotes: 'Saffron, Rose, Cardamom',
      heartNotes: 'Oud, Incense, Jasmine',
      baseNotes: 'Amber, Musk, Sandalwood, Leather',
      longevity: '12-18 hours',
      sillage: 'Very Strong',
      occasion: 'WEDDING,EID,RAMADAN',
      collection: 'LIMITED',
      coinsToAward: 80,
      isFeatured: true,
      isActive: true,
      enableWhatsapp: true,
      whatsappNumber: '+971-XX-XXXXXXX',
    },
  ];

  for (const product of limitedEditionProducts) {
    await createProduct(product);
  }

  // ====================================
  // SUMMARY
  // ====================================
  const totalProducts = oudProducts.length + oudOilProducts.length + perfumeProducts.length + allOverSprayProducts.length + limitedEditionProducts.length;

  console.log('\n' + '='.repeat(70));
  console.log('🎉 SEED COMPLETE!');
  console.log('='.repeat(70));
  console.log('\n📊 Summary:');
  console.log(`  - 1 Category added (limited-edition)`);
  console.log(`  - 1 Brand added (Antique Oud)`);
  console.log(`  - ${totalProducts} Products added:`);
  console.log(`    • Oud (Agarwood): ${oudProducts.length}`);
  console.log(`    • Oud Oils (Dehn Al Oud): ${oudOilProducts.length}`);
  console.log(`    • Perfumes: ${perfumeProducts.length}`);
  console.log(`    • All Over Sprays: ${allOverSprayProducts.length}`);
  console.log(`    • Limited Edition: ${limitedEditionProducts.length}`);
  console.log('='.repeat(70));
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
